[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements-web.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:${PORT:-5000} --workers 2 --timeout 120 run_web:app"

